.TH "RPC\-CHECK" "1" "September 2016" "" ""
.SH "NAME"
\fBrpc-check\fR \- check if a ethereum JSON RPC 2\.0  is online
.P
.RS 2
.nf
  rpc\-check <url> [\-\-json]
.fi
.RE
.SH DESCRIPTION
.P
.RS 2
.nf
<url>:
.fi
.RE
.P
  Check if a RPC node  node is currently online or available\. JSON output is
  also supported by passing the \fB\-\-json\fP flag\.

